import express from 'express';
import { createServer } from 'node:http';
import { WebSocketServer, WebSocket } from 'ws';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
app.use(express.json({ limit: '16kb' }));
app.use(express.static(__dirname));
app.get('/health', (_req, res) => res.json({ ok: true, service: 'secret-suspects' }));
app.get('*', (_req, res) => res.sendFile(path.join(__dirname, 'index.html')));
const httpServer = createServer(app);
const wss = new WebSocketServer({ server: httpServer, path: '/ws' });

const rooms = new Map();
const PORT = Number(process.env.PORT || 10000);
const MAX_PLAYERS = 10;
const CATEGORIES = ['cartoons', 'anime', 'movies', 'people', 'items'];
const ABILITIES = ['cancel', 'redirect', 'back'];
const names = ['Nova', 'Mango', 'Pixel', 'Orbit', 'Bubbles', 'Comet', 'Pico', 'Sunny', 'Mochi', 'Clover'];

const uid = (prefix = 'id') => `${prefix}_${crypto.randomBytes(5).toString('hex')}`;
const roomCode = () => {
  let code;
  do code = crypto.randomBytes(2).toString('hex').toUpperCase(); while (rooms.has(code));
  return code;
};
const now = () => Date.now();
const safeText = (value, max = 160) => String(value ?? '').replace(/[\u0000-\u001f\u007f]/g, '').trim().slice(0, max);
const normalize = (value) => safeText(value, 120).toLowerCase().normalize('NFKC').replace(/[أإآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ى/g, 'ي').replace(/[ًٌٍَُِّْـ]/g, '').replace(/[.,!?؟:;"'`()\[\]{}]/g, '').replace(/\s+/g, ' ');
function distance(a, b) { const row = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 1; i <= a.length; i++) { let prev = row[0]; row[0] = i; for (let j = 1; j <= b.length; j++) { const temp = row[j]; row[j] = Math.min(row[j] + 1, row[j - 1] + 1, prev + (a[i - 1] === b[j - 1] ? 0 : 1)); prev = temp; } } return row[b.length]; }
function matches(guess, actual) { const a = normalize(guess), b = normalize(actual); if (!a || !b) return false; if (a === b || a.includes(b) || b.includes(a)) return true; const maxLen = Math.max(a.length, b.length); return maxLen >= 5 && distance(a, b) <= Math.max(1, Math.floor(maxLen * 0.16)); }
function createPlayer(name, ws) { return { id: uid('p'), name: safeText(name, 24) || names[Math.floor(Math.random() * names.length)], color: `hsl(${Math.floor(Math.random() * 360)} 74% 66%)`, ws, connected: true, ready: false, spectator: false, eliminated: false, identity: '', identityLocked: false, abilities: Object.fromEntries(ABILITIES.map(a => [a, false])), questionAsked: false, questionReceived: false, suspicionDone: false, guesses: {}, submittedGuesses: false, vote: null, resumeToken: uid('resume') }; }
function defaults() { return { category: 'cartoons', language: 'ar', questionSeconds: 45, suspicionSeconds: 30, guessSeconds: 60, allowDuplicates: false, allowSkip: true, voteEnabled: true, voteThreshold: 2, sound: true, motion: true }; }
function alive(room) { return [...room.players.values()].filter(p => !p.eliminated && !p.spectator); }
function publicPlayer(p) { return { id: p.id, name: p.name, color: p.color, connected: p.connected, ready: p.ready, eliminated: p.eliminated, spectator: p.spectator }; }
function log(room, event) { room.log.push({ id: uid('e'), text: event, at: now() }); room.log = room.log.slice(-30); }
function phaseLabel(room) { return room.phase === 'lobby' ? 'lobby' : room.phase; }
function publicState(room, viewer) {
  const players = [...room.players.values()].map(publicPlayer);
  const current = room.currentTurn ? { questionerId: room.currentTurn.questionerId, targetId: room.currentTurn.targetId, kind: room.currentTurn.kind, endsAt: room.currentTurn.endsAt } : null;
  const vote = room.vote ? { initiatorId: room.vote.initiatorId, targetIds: room.vote.targetIds, votes: room.vote.closed ? room.vote.votes : Object.fromEntries(Object.keys(room.vote.votes).map(k => [k, room.vote.votes[k] ? 'submitted' : null])), endsAt: room.vote.endsAt, threshold: room.settings.voteThreshold, closed: room.vote.closed } : null;
  return { type: 'state', roomCode: room.code, leaderId: room.leaderId, me: viewer ? { id: viewer.id, name: viewer.name, identityLocked: viewer.identityLocked, identity: viewer.eliminated ? viewer.identity : undefined, abilities: viewer.abilities, guesses: viewer.guesses, submittedGuesses: viewer.submittedGuesses, resumeToken: viewer.resumeToken, eliminated: viewer.eliminated, spectator: viewer.spectator } : null, players, settings: room.settings, category: room.category, phase: phaseLabel(room), round: room.round, phaseEndsAt: room.phaseEndsAt, currentTurn: current, vote, results: room.results, winner: room.winner ? publicPlayer(room.winner) : null, winnerIdentity: room.winner?.identity, log: room.log, canStart: room.phase === 'lobby' && viewer?.id === room.leaderId, serverNow: now() };
}
function send(ws, payload) { if (ws?.readyState === WebSocket.OPEN) ws.send(JSON.stringify(payload)); }
function broadcast(room) { for (const p of room.players.values()) send(p.ws, publicState(room, p)); }
function error(ws, code, message) { send(ws, { type: 'error', code, message }); }
function findPlayer(room, id) { return room.players.get(id); }
function setTimer(room, seconds, callback) { if (room.timer) clearTimeout(room.timer); room.phaseEndsAt = now() + seconds * 1000; room.timer = setTimeout(callback, seconds * 1000 + 50); }
function startQuestion(room) {
  const players = alive(room); room.questionOrder = players.map((_, i) => ({ questionerId: players[i].id, targetId: players[(i + 1) % players.length].id })); room.questionIndex = 0; players.forEach(p => { p.questionAsked = false; p.questionReceived = false; p.suspicionDone = false; p.guesses = {}; p.submittedGuesses = false; p.vote = null; }); room.phase = 'question'; nextQuestion(room); }
function nextQuestion(room) { const item = room.questionOrder[room.questionIndex]; if (!item) return startSuspicion(room); const q = findPlayer(room, item.questionerId), t = findPlayer(room, item.targetId); if (!q || !t || q.eliminated || t.eliminated) { room.questionIndex++; return nextQuestion(room); } room.currentTurn = { kind: 'question', questionerId: q.id, targetId: t.id, originalTargetId: t.id, endsAt: 0 }; q.questionAsked = true; t.questionReceived = true; log(room, `${q.name} is asking ${t.name} a question.`); setTimer(room, room.settings.questionSeconds, () => finishQuestion(room)); broadcast(room); }
function finishQuestion(room) { if (room.phase !== 'question') return; room.questionIndex++; room.currentTurn = null; nextQuestion(room); }
function startSuspicion(room) { room.phase = 'suspicion'; room.suspicionIndex = 0; nextSuspicion(room); }
function nextSuspicion(room) { const players = alive(room); while (room.suspicionIndex < players.length) { const p = players[room.suspicionIndex]; const eligible = players.filter(t => t.id !== p.id && t.id !== room.questionOrder.find(x => x.questionerId === p.id)?.targetId); if (!eligible.length) { p.suspicionDone = true; room.suspicionIndex++; continue; } room.currentTurn = { kind: 'suspicion', questionerId: p.id, targetId: eligible[0].id, eligibleIds: eligible.map(x => x.id), endsAt: 0 }; log(room, `${p.name} has a suspicion question.`); setTimer(room, room.settings.suspicionSeconds, () => finishSuspicion(room)); broadcast(room); return; } room.currentTurn = null; startGuessing(room); }
function finishSuspicion(room) { if (room.phase !== 'suspicion') return; const p = findPlayer(room, room.currentTurn?.questionerId); if (p) p.suspicionDone = true; room.suspicionIndex++; room.currentTurn = null; nextSuspicion(room); }
function startGuessing(room) { room.phase = 'guessing'; room.phaseEndsAt = 0; for (const p of alive(room)) { p.guesses = {}; p.submittedGuesses = false; } setTimer(room, room.settings.guessSeconds, () => processGuesses(room)); broadcast(room); }
function processGuesses(room) { if (room.phase !== 'guessing') return; const correctByTarget = new Map(); for (const guesser of alive(room)) { for (const [targetId, guess] of Object.entries(guesser.guesses)) { const target = findPlayer(room, targetId); if (target && !target.eliminated && matches(guess, target.identity)) { if (!correctByTarget.has(target.id)) correctByTarget.set(target.id, []); correctByTarget.get(target.id).push(guesser.name); } } } const eliminated = []; for (const [targetId, by] of correctByTarget) { const target = findPlayer(room, targetId); if (target && !target.eliminated) { target.eliminated = true; eliminated.push({ playerId: target.id, name: target.name, identity: target.identity, guessedBy: by, round: room.round, reason: 'guess' }); } } room.results = eliminated; room.phase = eliminated.length ? 'results' : 'results'; room.currentTurn = null; log(room, eliminated.length ? `${eliminated.map(x => x.name).join(', ')} eliminated.` : 'No identities were revealed this round.'); if (alive(room).length <= 1) { room.winner = alive(room)[0] || null; room.phase = 'victory'; if (room.winner) log(room, `${room.winner.name} wins the match!`); } else setTimer(room, 12, () => nextRound(room)); broadcast(room); }
function nextRound(room) { if (room.phase !== 'results') return; room.round++; room.results = []; startQuestion(room); }
function finishVote(room, targetId = null) { if (!room.vote || room.vote.closed) return; room.vote.closed = true; const counts = {}; for (const value of Object.values(room.vote.votes)) if (value) counts[value] = (counts[value] || 0) + 1; const top = Object.entries(counts).sort((a, b) => b[1] - a[1]); const winner = top[0]; const passed = winner && winner[1] >= room.settings.voteThreshold && (!top[1] || winner[1] > top[1][1]); const target = passed ? findPlayer(room, winner[0]) : null; if (target) { target.eliminated = true; room.results = [{ playerId: target.id, name: target.name, identity: target.identity, guessedBy: [], round: room.round, reason: 'vote' }]; log(room, `${target.name} was eliminated by emergency vote.`); } else log(room, 'Emergency vote failed or ended in a tie.'); room.vote.result = { passed: !!target, targetId: target?.id || null, counts }; if (target && alive(room).length <= 1) { room.winner = alive(room)[0] || null; room.phase = 'victory'; } else { room.phase = 'results'; setTimer(room, 12, () => nextRound(room)); } broadcast(room); }
function startVote(room, initiator) { if (!room.settings.voteEnabled || !['results', 'lobby'].includes(room.phase)) return false; if (room.vote && !room.vote.closed) return false; const targets = alive(room).filter(p => p.id !== initiator.id).map(p => p.id); if (!targets.length) return false; room.vote = { initiatorId: initiator.id, targetIds: targets, votes: {}, endsAt: now() + 30_000, closed: false }; room.phase = 'voting'; log(room, `${initiator.name} called an emergency vote.`); setTimer(room, 30, () => finishVote(room)); broadcast(room); return true; }
function resetMatch(room) { room.phase = 'lobby'; room.round = 0; room.results = []; room.winner = null; room.vote = null; room.currentTurn = null; for (const p of room.players.values()) { p.ready = false; p.eliminated = false; p.spectator = false; p.identity = ''; p.identityLocked = false; p.abilities = Object.fromEntries(ABILITIES.map(a => [a, false])); p.guesses = {}; p.submittedGuesses = false; } log(room, 'A new match is ready.'); broadcast(room); }
function maybeStart(room) { if (room.phase !== 'lobby' || !alive(room).length || alive(room).some(p => !p.ready)) return; if (alive(room).some(p => !p.identityLocked)) return; room.round = 1; startQuestion(room); }
function handle(room, player, msg) {
  if (!msg || typeof msg.type !== 'string') return error(player.ws, 'BAD_MESSAGE', 'Invalid action.');
  if (msg.type === 'ping') return send(player.ws, { type: 'pong', at: now() });
  if (msg.type === 'set_settings') { if (room.leaderId !== player.id || room.phase !== 'lobby') return error(player.ws, 'NOT_ALLOWED', 'Only the leader can change lobby settings.'); room.settings = { ...room.settings, questionSeconds: Math.max(15, Math.min(90, Number(msg.settings?.questionSeconds) || 45)), suspicionSeconds: Math.max(15, Math.min(90, Number(msg.settings?.suspicionSeconds) || 30)), guessSeconds: Math.max(30, Math.min(120, Number(msg.settings?.guessSeconds) || 60)), category: CATEGORIES.includes(msg.settings?.category) ? msg.settings.category : room.settings.category, language: ['ar', 'en'].includes(msg.settings?.language) ? msg.settings.language : room.settings.language, allowDuplicates: !!msg.settings?.allowDuplicates, voteEnabled: msg.settings?.voteEnabled !== false }; room.category = room.settings.category; return broadcast(room); }
  if (msg.type === 'ready') { player.ready = !player.ready; broadcast(room); return; }
  if (msg.type === 'start_match') { if (room.leaderId !== player.id || room.players.size < 2) return error(player.ws, 'NOT_ALLOWED', 'The leader needs at least two players.'); if (alive(room).some(p => !p.ready)) return error(player.ws, 'NOT_READY', 'Everyone must be ready.'); room.phase = 'identity'; log(room, 'Identity selection has started.'); return broadcast(room); }
  if (msg.type === 'set_identity') { if (room.phase !== 'identity' || player.identityLocked) return error(player.ws, 'NOT_ALLOWED', 'Identity selection is closed.'); const identity = safeText(msg.identity, 80); if (!identity) return error(player.ws, 'EMPTY_IDENTITY', 'Enter a secret identity first.'); if (!room.settings.allowDuplicates && [...room.players.values()].some(p => p.id !== player.id && p.identityLocked && normalize(p.identity) === normalize(identity))) return error(player.ws, 'DUPLICATE_IDENTITY', 'That identity is already used.'); player.identity = identity; player.identityLocked = true; log(room, `${player.name} locked a secret identity.`); if ([...room.players.values()].filter(p => !p.spectator).every(p => p.identityLocked)) { room.round = 1; startQuestion(room); } else broadcast(room); return; }
  if (msg.type === 'done_turn') { if (!room.currentTurn || ![room.currentTurn.questionerId, room.currentTurn.targetId].includes(player.id)) return error(player.ws, 'NOT_YOUR_TURN', 'This turn is not waiting for you.'); if (room.phase === 'question') return finishQuestion(room); if (room.phase === 'suspicion') return finishSuspicion(room); }
  if (msg.type === 'use_ability') { const turn = room.currentTurn; if (!turn || room.phase !== 'question' || turn.targetId !== player.id || player.abilities[msg.ability]) return error(player.ws, 'ABILITY_UNAVAILABLE', 'This ability cannot be used now.'); if (!ABILITIES.includes(msg.ability)) return error(player.ws, 'ABILITY_UNAVAILABLE', 'Unknown ability.'); if (msg.ability === 'cancel') { player.abilities.cancel = true; log(room, `${player.name} cancelled the question.`); return finishQuestion(room); } if (msg.ability === 'back') { player.abilities.back = true; const q = findPlayer(room, turn.questionerId); turn.targetId = q.id; turn.originalTargetId = q.id; turn.backAtYou = true; log(room, `${player.name} used Back at You.`); return broadcast(room); } if (msg.ability === 'redirect') { const target = findPlayer(room, msg.targetId); if (!target || target.eliminated || target.id === player.id || target.id === turn.questionerId) return error(player.ws, 'INVALID_TARGET', 'Choose an eligible player.'); player.abilities.redirect = true; turn.targetId = target.id; turn.eligibleIds = []; log(room, `${player.name} redirected the question.`); return broadcast(room); } }
  if (msg.type === 'submit_suspicion_target') { if (room.phase !== 'suspicion' || room.currentTurn?.questionerId !== player.id) return error(player.ws, 'NOT_YOUR_TURN', 'Wait for your suspicion turn.'); const target = findPlayer(room, msg.targetId); if (!target || !room.currentTurn.eligibleIds.includes(target.id)) return error(player.ws, 'INVALID_TARGET', 'Choose an eligible target.'); room.currentTurn.targetId = target.id; return broadcast(room); }
  if (msg.type === 'submit_guess') { if (room.phase !== 'guessing' || player.eliminated || player.submittedGuesses) return error(player.ws, 'NOT_ALLOWED', 'Guessing is closed for you.'); const target = findPlayer(room, msg.targetId); const guess = safeText(msg.identity, 80); if (!target || target.eliminated || target.id === player.id) return error(player.ws, 'INVALID_TARGET', 'Choose a living opponent.'); if (!guess && !room.settings.allowSkip) return error(player.ws, 'EMPTY_GUESS', 'Enter a guess.'); player.guesses[target.id] = guess; return broadcast(room); }
  if (msg.type === 'finish_guesses') { if (room.phase !== 'guessing') return error(player.ws, 'NOT_ALLOWED', 'Guessing is not active.'); player.submittedGuesses = true; if (alive(room).every(p => p.submittedGuesses)) processGuesses(room); else broadcast(room); return; }
  if (msg.type === 'call_vote') { if (!startVote(room, player)) return error(player.ws, 'VOTE_UNAVAILABLE', 'Voting is not available right now.'); return; }
  if (msg.type === 'cast_vote') { if (room.phase !== 'voting' || !room.vote || room.vote.closed) return error(player.ws, 'VOTE_CLOSED', 'This vote is closed.'); const target = msg.targetId === null ? null : findPlayer(room, msg.targetId); if (target && !room.vote.targetIds.includes(target.id)) return error(player.ws, 'INVALID_TARGET', 'Invalid vote target.'); room.vote.votes[player.id] = target?.id || null; if (alive(room).every(p => Object.hasOwn(room.vote.votes, p.id))) finishVote(room); else broadcast(room); return; }
  if (msg.type === 'play_again') { if (room.phase !== 'victory' || player.id !== room.leaderId) return error(player.ws, 'NOT_ALLOWED', 'Only the leader can restart.'); resetMatch(room); return; }
  if (msg.type === 'leave') { player.connected = false; player.spectator = true; if (room.leaderId === player.id) room.leaderId = alive(room)[0]?.id || null; broadcast(room); return; }
}
function attach(room, player, ws) { player.ws = ws; player.connected = true; player.spectator = player.eliminated; ws.playerId = player.id; ws.roomCode = room.code; send(ws, publicState(room, player)); }
function createRoom(ws, name) { const p = createPlayer(name, ws); const code = roomCode(); const room = { code, players: new Map([[p.id, p]]), leaderId: p.id, category: 'cartoons', settings: defaults(), phase: 'lobby', round: 0, log: [], results: [], winner: null, vote: null, timer: null, currentTurn: null }; rooms.set(code, room); attach(room, p, ws); log(room, `${p.name} created the room.`); broadcast(room); }
wss.on('connection', (ws) => { ws.isAlive = true; ws.on('pong', () => { ws.isAlive = true; }); ws.on('message', raw => { try { const msg = JSON.parse(raw.toString()); if (msg.type === 'create_room') return createRoom(ws, msg.name); if (msg.type === 'join_room') { const code = safeText(msg.roomCode, 8).toUpperCase(), room = rooms.get(code); if (!room) return error(ws, 'ROOM_NOT_FOUND', 'Room not found.'); if (room.phase !== 'lobby' && room.phase !== 'identity' && !msg.resumeToken) return error(ws, 'ROOM_ACTIVE', 'This match is already active.'); let p = [...room.players.values()].find(x => x.resumeToken === msg.resumeToken && msg.resumeToken); if (!p) { if (room.players.size >= MAX_PLAYERS || room.phase !== 'lobby') return error(ws, 'ROOM_FULL', 'This room cannot accept a new player now.'); p = createPlayer(msg.name, ws); room.players.set(p.id, p); log(room, `${p.name} joined the room.`); } attach(room, p, ws); return broadcast(room); } if (!ws.roomCode) return error(ws, 'NOT_IN_ROOM', 'Join a room first.'); const room = rooms.get(ws.roomCode), player = room?.players.get(ws.playerId); if (!room || !player) return error(ws, 'ROOM_NOT_FOUND', 'Room not found.'); handle(room, player, msg); } catch { error(ws, 'BAD_MESSAGE', 'Invalid message.'); } }); ws.on('close', () => { ws.isAlive = false; const room = rooms.get(ws.roomCode); const p = room?.players.get(ws.playerId); if (p && p.ws === ws) { p.connected = false; log(room, `${p.name} disconnected.`); broadcast(room); } }); });
setInterval(() => { for (const ws of wss.clients) { if (!ws.isAlive) ws.terminate(); ws.isAlive = false; ws.ping(); } for (const [code, room] of rooms) { const connected = [...room.players.values()].some(p => p.connected); if (!connected && now() - (room.lastActivity || now()) > 60 * 60 * 1000) rooms.delete(code); } }, 30_000);
httpServer.listen(PORT, '0.0.0.0', () => console.log(`Secret Suspects listening on ${PORT}`));
